function pug_attr(t,e,n,f){return!1!==e&&null!=e&&(e||"class"!==t&&"style"!==t)?!0===e?" "+(f?t:t+'="'+t+'"'):("function"==typeof e.toJSON&&(e=e.toJSON()),"string"==typeof e||(e=JSON.stringify(e),n||-1===e.indexOf('"'))?(n&&(e=pug_escape(e))," "+t+'="'+e+'"'):" "+t+"='"+e.replace(/'/g,"&#39;")+"'"):""}
function pug_escape(e){var a=""+e,t=pug_match_html.exec(a);if(!t)return e;var r,c,n,s="";for(r=t.index,c=0;r<a.length;r++){switch(a.charCodeAt(r)){case 34:n="&quot;";break;case 38:n="&amp;";break;case 60:n="&lt;";break;case 62:n="&gt;";break;default:continue}c!==r&&(s+=a.substring(c,r)),c=r+1,s+=n}return c!==r?s+a.substring(c,r):s}
var pug_match_html=/["&<>]/;
function pug_rethrow(n,e,r,t){if(!(n instanceof Error))throw n;if(!("undefined"==typeof window&&e||t))throw n.message+=" on line "+r,n;try{t=t||require("fs").readFileSync(e,"utf8")}catch(e){pug_rethrow(n,null,r)}var i=3,a=t.split("\n"),o=Math.max(r-i,0),h=Math.min(a.length,r+i),i=a.slice(o,h).map(function(n,e){var t=e+o+1;return(t==r?"  > ":"    ")+t+"| "+n}).join("\n");throw n.path=e,n.message=(e||"Pug")+":"+r+"\n"+i+"\n\n"+n.message,n}function loginTemplate(locals) {var pug_html = "", pug_mixins = {}, pug_interp;var pug_debug_filename, pug_debug_line;try {;pug_debug_line = 1;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "\u003Cdiv class=\"login\" id=\"login\"\u003E";
;pug_debug_line = 2;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "\u003Cdiv class=\"app__header\"\u003E";
;pug_debug_line = 3;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "\u003Ca class=\"a menu__item item__icon item__icon_chat app__header_title\" href=\"#\" title=\"Главная страница\"\u003E";
;pug_debug_line = 3;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "чат\u003C\u002Fa\u003E";
;pug_debug_line = 4;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "\u003Cspan class=\"app__header_user\" id=\"username\"\u003E\u003C\u002Fspan\u003E";
;pug_debug_line = 5;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "\u003Ca class=\"a menu__item item__icon item__icon_login\" title=\"Войти в чат\"\u003E";
;pug_debug_line = 5;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "войти\u003C\u002Fa\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 7;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "\u003Cinput" + (" class=\"input_radio input_radio-login\""+" type=\"radio\" name=\"login\" id=\"radio-login\""+pug_attr("checked", true, true, false)+pug_attr("hidden", true, true, false)) + "\u002F\u003E";
;pug_debug_line = 8;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "\u003Cinput" + (" class=\"input_radio input_radio-sign\""+" type=\"radio\" name=\"login\" id=\"radio-sign\""+pug_attr("hidden", true, true, false)) + "\u002F\u003E";
;pug_debug_line = 9;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "\u003Cinput" + (" class=\"input_radio input_radio-forgot\""+" type=\"radio\" name=\"login\" id=\"radio-forgot\""+pug_attr("hidden", true, true, false)) + "\u002F\u003E";
;pug_debug_line = 10;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "\u003Cdiv class=\"labels\"\u003E";
;pug_debug_line = 11;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "\u003Clabel class=\"label__radio login__label_login\" for=\"radio-login\"\u003E";
;pug_debug_line = 11;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "Войти\u003C\u002Flabel\u003E";
;pug_debug_line = 12;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "\u003Clabel class=\"label__radio login__label_sign\" for=\"radio-sign\"\u003E";
;pug_debug_line = 12;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "Регистрация\u003C\u002Flabel\u003E";
;pug_debug_line = 13;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "\u003Clabel class=\"label__radio login__label_forgot\" for=\"radio-forgot\"\u003E";
;pug_debug_line = 13;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "Восстановить\u003C\u002Flabel\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 15;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "\u003Cdiv class=\"login__content_wrapper\"\u003E";
;pug_debug_line = 16;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "\u003Cform class=\"form login__content login__content_login\" name=\"login\"\u003E";
;pug_debug_line = 17;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "\u003Clabel class=\"label label__user\"\u003E";
;pug_debug_line = 18;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "\u003Cspan class=\"label__text\"\u003E";
;pug_debug_line = 18;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "Логин\u003C\u002Fspan\u003E";
;pug_debug_line = 19;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "\u003Cinput class=\"input input_user-name\" type=\"text\" data-tooltip=\"Введите логин\" name=\"user-name\"\u002F\u003E\u003C\u002Flabel\u003E";
;pug_debug_line = 20;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "\u003Clabel class=\"label label__password label__password_lock\"\u003E";
;pug_debug_line = 21;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "\u003Cspan class=\"label__text\"\u003E";
;pug_debug_line = 21;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "Пароль\u003C\u002Fspan\u003E";
;pug_debug_line = 22;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "\u003Cinput class=\"input input_password\" type=\"password\" data-tooltip=\"Введите пароль\" name=\"pass\"\u002F\u003E\u003C\u002Flabel\u003E";
;pug_debug_line = 23;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "\u003Cinput class=\"button button_form\" type=\"submit\" value=\"Войти\" id=\"login-button\"\u002F\u003E\u003C\u002Fform\u003E";
;pug_debug_line = 25;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "\u003Cform class=\"form login__content login__content_sign\" name=\"sign\"\u003E";
;pug_debug_line = 26;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "\u003Clabel class=\"label label__user\"\u003E";
;pug_debug_line = 27;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "\u003Cspan class=\"label__text\"\u003E";
;pug_debug_line = 27;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "Логин\u003C\u002Fspan\u003E";
;pug_debug_line = 28;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "\u003Cinput class=\"input input_user-name\" type=\"text\" data-tooltip=\"Введите логин\" name=\"user-name\"\u002F\u003E\u003C\u002Flabel\u003E";
;pug_debug_line = 29;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "\u003Clabel class=\"label label__email\"\u003E";
;pug_debug_line = 30;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "\u003Cspan class=\"label__text\"\u003E";
;pug_debug_line = 30;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "E-mail\u003C\u002Fspan\u003E";
;pug_debug_line = 31;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "\u003Cinput class=\"input input_email\" type=\"text\" data-tooltip=\"Введите Ваш e-mail\" name=\"e-mail\"\u002F\u003E\u003C\u002Flabel\u003E";
;pug_debug_line = 32;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "\u003Clabel class=\"label label__password label__password_lock\"\u003E";
;pug_debug_line = 33;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "\u003Cspan class=\"label__text\"\u003E";
;pug_debug_line = 33;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "Пароль\u003C\u002Fspan\u003E";
;pug_debug_line = 34;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "\u003Cinput class=\"input input_password\" type=\"password\" data-tooltip=\"Введите пароль\" name=\"pass\"\u002F\u003E\u003C\u002Flabel\u003E";
;pug_debug_line = 35;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "\u003Cinput class=\"button button_form\" type=\"submit\" value=\"Зарегистрироваться\" id=\"sign-button\"\u002F\u003E\u003C\u002Fform\u003E";
;pug_debug_line = 37;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "\u003Cform class=\"form login__content  login__content_forgot\" name=\"forgot\"\u003E";
;pug_debug_line = 38;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "\u003Clabel class=\"label label__user\"\u003E";
;pug_debug_line = 39;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "\u003Cspan class=\"label__text\"\u003E";
;pug_debug_line = 39;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "Логин\u003C\u002Fspan\u003E";
;pug_debug_line = 40;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "\u003Cinput class=\"input input_user-name\" type=\"text\" data-tooltip=\"Введите логин\" name=\"user-name\"\u002F\u003E\u003C\u002Flabel\u003E";
;pug_debug_line = 41;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "\u003Clabel class=\"label label__email\"\u003E";
;pug_debug_line = 42;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "\u003Cspan class=\"label__text\"\u003E";
;pug_debug_line = 42;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "E-mail\u003C\u002Fspan\u003E";
;pug_debug_line = 43;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "\u003Cinput class=\"input input_email\" type=\"text\" data-tooltip=\"Введите Ваш e-mail\" name=\"e-mail\"\u002F\u003E\u003C\u002Flabel\u003E";
;pug_debug_line = 44;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "\u003Clabel class=\"label label__password label__password_lock\"\u003E";
;pug_debug_line = 45;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "\u003Cspan class=\"label__text\"\u003E";
;pug_debug_line = 45;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "Новый пароль\u003C\u002Fspan\u003E";
;pug_debug_line = 46;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "\u003Cinput class=\"input input_password\" type=\"pass\" data-tooltip=\"Введите новый пароль\" name=\"pass\"\u002F\u003E\u003C\u002Flabel\u003E";
;pug_debug_line = 48;pug_debug_filename = "c:\\Users\\God Father\\projects\\chat\\components\\login\\login.templ.pug";
pug_html = pug_html + "\u003Cinput class=\"button button_form\" type=\"submit\" value=\"Восстановить\" id=\"forgot-button\"\u002F\u003E\u003C\u002Fform\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E";} catch (err) {pug_rethrow(err, pug_debug_filename, pug_debug_line);};return pug_html;}